name: My Workflow

on:
  push:
    paths:
    - build.gradle.txt
    branches:
    - master

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ajay0688/action-tagging@master
      with:
        source_file: "build.gradle.txt"
        tag_prefix: "v"
        extraction_regex: "version\\s*=\\s*\\d+.\\d+.\\d+"
