name: My Workflow

on:
  push:
    paths:
    - build.gradle.txt
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ajay0688/action-tagging@master
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        source_file: "build.gradle.txt"
        extraction_regex: "(version)\s*(=)\s*(\d+)(.)(\d+)(.)(\d+)"